const test=require('node:test'),assert=require('node:assert/strict');
const {configureWebContents,webEquivalent,partitionFor,webPreferences}=require('./web-session.cjs');
function fixture(){const events={},loads=[],notices=[];let open;const contents={on:(k,f)=>events[k]=f,setWindowOpenHandler:f=>open=f,loadURL:async url=>loads.push(url)};configureWebContents(contents,{},m=>notices.push(m));return {events,loads,notices,open:args=>open(args)};}
test('desktop launch in a hidden frame is cancelled and Slack opens on web',async()=>{const f=fixture();let cancelled=false;f.events['will-frame-navigate']({url:'slack://channel?team=T123&id=C456',preventDefault:()=>cancelled=true});await Promise.resolve();assert.ok(cancelled);assert.deepEqual(f.loads,['https://app.slack.com/client/T123/C456']);});
test('redirect and popup attempts cannot launch unknown native apps',()=>{const f=fixture();let cancelled=false;f.events['will-redirect']({url:'zoommtg://zoom.us/join',preventDefault:()=>cancelled=true});assert.ok(cancelled);assert.equal(f.open({url:'someapp://open'}).action,'deny');assert.equal(f.loads.length,0);assert.equal(f.notices.length,2);});
test('web navigation is untouched and authentication popups stay Hearth owned',()=>{const f=fixture();f.events['will-frame-navigate']({url:'https://example.com/',preventDefault:()=>assert.fail('web link blocked')});const popup=f.open({url:'https://accounts.google.com/'});assert.equal(popup.action,'allow');assert.ok(popup.overrideBrowserWindowOptions.parent);assert.equal(popup.overrideBrowserWindowOptions.webPreferences.partition,'persist:services');});
test('mapped app links preserve destination and reject lookalike Teams hosts',()=>{assert.equal(webEquivalent('notion://www.notion.so/a-page#section'),'https://www.notion.so/a-page#section');assert.equal(webEquivalent('msteams://teams.microsoft.com/l/meetup-join/123'),'https://teams.microsoft.com/l/meetup-join/123');assert.equal(webEquivalent('msteams://teams.microsoft.com.evil.test/a'),null);});
test('Slack workspace launcher opens web messages in the existing pane without a popup',async()=>{const f=fixture();assert.equal(f.open({url:'https://example.slack.com/ssb/redirect'}).action,'deny');await Promise.resolve();assert.deepEqual(f.loads,['https://example.slack.com/messages']);});
test('repeated native Slack launches do not reload the page forever',async()=>{const f=fixture();for(let i=0;i<3;i++){f.open({url:'slack://open?team=T123'});await Promise.resolve();}assert.deepEqual(f.loads,['https://app.slack.com/client/T123']);});
test('Slack popups use the root pane, including links from login children',async()=>{const events={},loads=[];const root={on:(k,f)=>events[k]=f,setWindowOpenHandler:()=>{},loadURL:async u=>loads.push(u)};configureWebContents(root,{});let childOpen;events['did-create-window']({webContents:{on:()=>{},setWindowOpenHandler:f=>childOpen=f}});assert.equal(childOpen({url:'https://app.slack.com/client/T123'}).action,'deny');await Promise.resolve();assert.deepEqual(loads,['https://app.slack.com/client/T123']);});
test('browser profiles share only their intended persistent partitions',()=>{assert.equal(partitionFor('shared','gmail'),'persist:services');assert.equal(partitionFor('personal','gmail'),'persist:profile-personal');assert.equal(partitionFor('work','slack'),'persist:profile-work');assert.equal(partitionFor('isolated','bank'),partitionFor('isolated','bank'));assert.notEqual(partitionFor('isolated','bank'),partitionFor('isolated','admin'));assert.throws(()=>webPreferences('unknown'));});
test('OAuth popups inherit the app profile',()=>{const events={};let open;const contents={on:(key,fn)=>events[key]=fn,setWindowOpenHandler:fn=>open=fn,loadURL:async()=>{}};const preferences=webPreferences('personal','gmail');configureWebContents(contents,{},()=>{},contents,preferences);const popup=open({url:'https://accounts.google.com/'});assert.equal(popup.overrideBrowserWindowOptions.webPreferences.partition,'persist:profile-personal');});
test('ad-hoc addresses use an in-memory partition that is never persisted',()=>{const {ephemeralWebPreferences}=require('./web-session.cjs');const prefs=ephemeralWebPreferences('https://example.com/');assert.ok(!prefs.partition.startsWith('persist:'));assert.equal(prefs.sandbox,true);assert.equal(prefs.nodeIntegration,false);assert.equal(prefs.partition,ephemeralWebPreferences('https://example.com/').partition);assert.notEqual(prefs.partition,ephemeralWebPreferences('https://other.example/').partition);});
test('the Browser app uses its own persistent sandboxed partition, separate from saved apps',()=>{const {browserWebPreferences,BROWSER_PARTITION}=require('./web-session.cjs');const prefs=browserWebPreferences();assert.equal(prefs.partition,BROWSER_PARTITION);assert.ok(prefs.partition.startsWith('persist:'));assert.equal(prefs.sandbox,true);assert.equal(prefs.nodeIntegration,false);assert.notEqual(prefs.partition,partitionFor('shared'));assert.notEqual(prefs.partition,partitionFor('isolated','browser'));});
