const NS='http://www.w3.org/2000/svg';
const colours=['#26364a','#e8875b','#5d8f77','#6f74b8','#c7839d'];
const noteColours=['#fff0a8','#dcecff','#dff2df','#f7dfe5'];
const clone=value=>JSON.parse(JSON.stringify(value));
// Sticky notes hold a small amount of rich text. It is sanitised both when loaded and when saved, so only these tags survive.
const NOTE_TAGS=['b','strong','i','em','u','s','strike','br','p','div','ul','ol','li','h3'];
const cleanNoteHTML=html=>(typeof DOMPurify!=='undefined'?DOMPurify.sanitize(String(html || ''),{ALLOWED_TAGS:NOTE_TAGS,ALLOWED_ATTR:[]}):'').slice(0,20000);
const escapeHTML=text=>String(text || '').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const noteHTML=value=>value.html!==undefined?cleanNoteHTML(value.html):escapeHTML(value.text).replace(/\n/g,'<br>');
const NOTE_TOOLS=[['bold','B','Bold (⌘B)'],['italic','I','Italic (⌘I)'],['underline','U','Underline (⌘U)'],['strikeThrough','S','Strikethrough'],['insertUnorderedList','•','Bullet list'],['insertOrderedList','1.','Numbered list'],['heading','H','Heading']];

export function createWhiteboard({save,notice=()=>{}}){
 const canvas=document.getElementById('whiteboard'),svg=document.getElementById('whiteboard-svg'),layer=document.getElementById('whiteboard-layer');
 let board={items:[],camera:{x:0,y:0,zoom:1}},tool='select',colour=colours[0],selected=null,gesture=null,panStart=null,saveTimer=null,history=[];
 const uid=()=>crypto.randomUUID();
 const point=event=>{const rect=canvas.getBoundingClientRect(),camera=board.camera;return {x:camera.x+(event.clientX-rect.left)/camera.zoom,y:camera.y+(event.clientY-rect.top)/camera.zoom};};
 const item=id=>board.items.find(value=>value.id===id);
 function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(clone(board)).catch(error=>notice(error.message)),300);}
 function remember(){history.push(clone(board));if(history.length>40)history.shift();}
 function select(id){selected=id;render();}
 function svgElement(name,attributes){const element=document.createElementNS(NS,name);for(const [key,value] of Object.entries(attributes))element.setAttribute(key,String(value));return element;}
 function attachSelection(element,value){element.classList.add('board-object');if(value.id===selected)element.classList.add('selected');element.addEventListener('pointerdown',event=>{if(tool!=='select')return;event.stopPropagation();startMove(event,value.id);});}
 function renderVector(value){let element;if(value.type==='path')element=svgElement('polyline',{points:value.points.map(p=>p.join(',')).join(' '),fill:'none',stroke:value.color,'stroke-width':value.width || 3,'stroke-linecap':'round','stroke-linejoin':'round'});if(value.type==='rectangle')element=svgElement('rect',{x:Math.min(value.x1,value.x2),y:Math.min(value.y1,value.y2),width:Math.abs(value.x2-value.x1),height:Math.abs(value.y2-value.y1),rx:8,fill:'none',stroke:value.color,'stroke-width':3});if(value.type==='ellipse')element=svgElement('ellipse',{cx:(value.x1+value.x2)/2,cy:(value.y1+value.y2)/2,rx:Math.abs(value.x2-value.x1)/2,ry:Math.abs(value.y2-value.y1)/2,fill:'none',stroke:value.color,'stroke-width':3});if(value.type==='arrow')element=svgElement('line',{x1:value.x1,y1:value.y1,x2:value.x2,y2:value.y2,stroke:value.color,'stroke-width':3,'stroke-linecap':'round','marker-end':'url(#board-arrow)'});if(!element)return;element.dataset.id=value.id;attachSelection(element,value);svg.append(element);}
 function textItem(value){const wrap=document.createElement('div');wrap.className='board-text-item'+(value.id===selected?' selected':'');wrap.style.left=value.x+'px';wrap.style.top=value.y+'px';wrap.dataset.id=value.id;const grip=document.createElement('button');grip.className='board-grip';grip.textContent='⠿';grip.title='Move';grip.onpointerdown=event=>{event.stopPropagation();startMove(event,value.id);};const area=document.createElement('textarea');area.value=value.text || '';area.placeholder='Type here…';area.style.color=value.color;area.onpointerdown=event=>event.stopPropagation();area.onfocus=()=>{selected=value.id;wrap.classList.add('selected');};area.oninput=()=>{value.text=area.value;queueSave();};wrap.append(grip,area);return wrap;}
 function noteItem(value){
  const wrap=document.createElement('div');wrap.className='board-postit'+(value.id===selected?' selected':'');wrap.style.left=value.x+'px';wrap.style.top=value.y+'px';wrap.style.width=(value.w || 220)+'px';wrap.style.height=(value.h || 170)+'px';wrap.style.background=value.color;wrap.style.transform=`rotate(${value.rotation || 0}deg)`;wrap.dataset.id=value.id;
  const grip=document.createElement('button');grip.className='board-grip';grip.textContent='⠿';grip.title='Move note';grip.onpointerdown=event=>{event.stopPropagation();startMove(event,value.id);};
  const tools=document.createElement('div');tools.className='board-note-tools';tools.setAttribute('role','toolbar');tools.setAttribute('aria-label','Note formatting');
  const body=document.createElement('div');body.className='board-note-body';body.contentEditable='true';body.spellcheck=false;body.dataset.placeholder='Write something…';body.innerHTML=noteHTML(value);
  for(const [command,label,title] of NOTE_TOOLS){const button=document.createElement('button');button.type='button';button.className='board-note-tool board-note-tool-'+command;button.textContent=label;button.title=title;button.onpointerdown=event=>{event.preventDefault();event.stopPropagation();};button.onclick=event=>{event.stopPropagation();body.focus();if(command==='heading'){const block=document.queryCommandValue('formatBlock');document.execCommand('formatBlock',false,/h3/i.test(block)?'div':'h3');}else document.execCommand(command,false,null);commit();};tools.append(button);}
  const commit=()=>{value.html=cleanNoteHTML(body.innerHTML);value.text=body.innerText.trim();queueSave();};
  body.onpointerdown=event=>event.stopPropagation();body.onfocus=()=>{selected=value.id;wrap.classList.add('selected');document.getElementById('board-delete').disabled=false;};
  body.oninput=commit;body.onblur=()=>{const clean=cleanNoteHTML(body.innerHTML);if(clean!==body.innerHTML)body.innerHTML=clean;};
  body.addEventListener('paste',event=>{event.preventDefault();const text=(event.clipboardData || window.clipboardData).getData('text/plain');document.execCommand('insertText',false,text);});
  const handle=document.createElement('button');handle.className='board-resize';handle.title='Resize note';handle.setAttribute('aria-label','Resize note');handle.onpointerdown=event=>{event.stopPropagation();event.preventDefault();startResize(event,value.id,wrap);};
  wrap.append(grip,tools,body,handle);return wrap;
 }
 function startResize(event,id,wrap){const value=item(id);if(!value)return;selected=id;remember();const start=point(event),w0=value.w || 220,h0=value.h || 170;const move=next=>{const here=point(next);value.w=Math.round(Math.max(120,Math.min(1200,w0+(here.x-start.x))));value.h=Math.round(Math.max(90,Math.min(1200,h0+(here.y-start.y))));wrap.style.width=value.w+'px';wrap.style.height=value.h+'px';};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);queueSave();};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true});}
 function applyCamera(){const {x,y,zoom}=board.camera,width=canvas.clientWidth || 1,height=canvas.clientHeight || 1;svg.setAttribute('viewBox',`${x} ${y} ${width/zoom} ${height/zoom}`);layer.style.transform=`translate(${-x*zoom}px,${-y*zoom}px) scale(${zoom})`;canvas.style.backgroundSize=`${22*zoom}px ${22*zoom}px`;canvas.style.backgroundPosition=`${-x*zoom}px ${-y*zoom}px`;document.getElementById('board-zoom-label').textContent=Math.round(zoom*100)+'%';}
 function render(){for(const node of [...svg.children])if(node.tagName!=='defs')node.remove();layer.replaceChildren();for(const value of board.items){if(['path','rectangle','ellipse','arrow'].includes(value.type))renderVector(value);else if(value.type==='note')layer.append(noteItem(value));else if(value.type==='text')layer.append(textItem(value));}document.getElementById('board-delete').disabled=!selected;document.getElementById('board-undo').disabled=!history.length;applyCamera();}
 const dirtyObjects=new Set();let paintFrame=null;
 function paintObject(id){dirtyObjects.add(id);if(paintFrame!==null)return;paintFrame=requestAnimationFrame(()=>{paintFrame=null;for(const key of dirtyObjects){const value=item(key);if(!value)continue;const old=svg.querySelector('[data-id="'+CSS.escape(key)+'"]');if(old){old.remove();renderVector(value);}else{const node=layer.querySelector('[data-id="'+CSS.escape(key)+'"]');if(node){node.style.left=value.x+'px';node.style.top=value.y+'px';}}}dirtyObjects.clear();});}
 function updateEndpoint(value,dx,dy){if(value.type==='path')value.points=value.points.map(([x,y])=>[x+dx,y+dy]);else if(['rectangle','ellipse','arrow'].includes(value.type)){value.x1+=dx;value.x2+=dx;value.y1+=dy;value.y2+=dy;}else{value.x+=dx;value.y+=dy;}}
 function startMove(event,id){const value=item(id);if(!value)return;selected=id;remember();const start=point(event),original=clone(value);const move=next=>{const here=point(next),index=board.items.findIndex(entry=>entry.id===id);if(index<0)return;const current=clone(original);updateEndpoint(current,here.x-start.x,here.y-start.y);board.items[index]=current;paintObject(id);};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);queueSave();};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true});render();}
 function addAt(position){remember();let value;if(tool==='note')value={id:uid(),type:'note',x:position.x-20,y:position.y-20,w:220,h:170,text:'',color:noteColours[board.items.filter(v=>v.type==='note').length%noteColours.length],rotation:(Math.random()*3-1.5).toFixed(2)};if(tool==='text')value={id:uid(),type:'text',x:position.x,y:position.y,text:'',color:colour};if(!value)return false;board.items.push(value);selected=value.id;setTool('select');render();queueSave();requestAnimationFrame(()=>layer.querySelector(`[data-id="${value.id}"] textarea, [data-id="${value.id}"] .board-note-body`)?.focus());return true;}
 function pointerDown(event){if(event.button!==0)return;if(tool==='hand'){panStart={clientX:event.clientX,clientY:event.clientY,camera:clone(board.camera)};svg.setPointerCapture(event.pointerId);return;}const start=point(event);if(['note','text'].includes(tool)){addAt(start);return;}if(tool==='select'){selected=null;render();return;}remember();const value=tool==='pen'?{id:uid(),type:'path',points:[[start.x,start.y]],color:colour,width:3}:{id:uid(),type:tool,x1:start.x,y1:start.y,x2:start.x,y2:start.y,color:colour};board.items.push(value);gesture=value.id;svg.setPointerCapture(event.pointerId);render();}
 function pointerMove(event){if(panStart){board.camera.x=panStart.camera.x-(event.clientX-panStart.clientX)/board.camera.zoom;board.camera.y=panStart.camera.y-(event.clientY-panStart.clientY)/board.camera.zoom;applyCamera();return;}if(!gesture)return;const value=item(gesture),here=point(event);if(value.type==='path'){const last=value.points.at(-1);if(Math.hypot(here.x-last[0],here.y-last[1])>2)value.points.push([here.x,here.y]);}else{value.x2=here.x;value.y2=here.y;}paintObject(value.id);}
 function pointerUp(event){if(!gesture && !panStart)return;gesture=null;panStart=null;try{svg.releasePointerCapture(event.pointerId);}catch{}queueSave();}
 function setTool(value){tool=value;for(const button of document.querySelectorAll('[data-board-tool]'))button.setAttribute('aria-pressed',button.dataset.boardTool===value);canvas.dataset.tool=value;}
 function setBoard(value){board=value && Array.isArray(value.items)?clone(value):{items:[]};board.camera=board.camera || {x:0,y:0,zoom:1};selected=null;history=[];render();}
 function zoomAt(next,clientX=canvas.getBoundingClientRect().left+canvas.clientWidth/2,clientY=canvas.getBoundingClientRect().top+canvas.clientHeight/2){const before=point({clientX,clientY}),rect=canvas.getBoundingClientRect();board.camera.zoom=Math.max(.25,Math.min(2.5,next));board.camera.x=before.x-(clientX-rect.left)/board.camera.zoom;board.camera.y=before.y-(clientY-rect.top)/board.camera.zoom;applyCamera();queueSave();}
 for(const button of document.querySelectorAll('[data-board-tool]'))button.onclick=()=>setTool(button.dataset.boardTool);
 for(const [index,button] of [...document.querySelectorAll('.board-swatch')].entries()){button.style.background=colours[index];button.onclick=()=>{colour=colours[index];document.querySelectorAll('.board-swatch').forEach(value=>value.classList.toggle('active',value===button));};}
 document.querySelector('.board-swatch')?.classList.add('active');
 document.getElementById('board-delete').onclick=()=>{if(!selected)return;remember();board.items=board.items.filter(value=>value.id!==selected);selected=null;render();queueSave();};
 document.getElementById('board-undo').onclick=()=>{if(!history.length)return;board=history.pop();selected=null;render();queueSave();};
 document.getElementById('board-clear').onclick=()=>{if(!board.items.length || !confirm('Clear everything from this whiteboard?'))return;remember();board={items:[],camera:clone(board.camera)};selected=null;render();queueSave();};
 document.getElementById('board-zoom-out').onclick=()=>zoomAt(board.camera.zoom/1.2);document.getElementById('board-zoom-in').onclick=()=>zoomAt(board.camera.zoom*1.2);document.getElementById('board-home-view').onclick=()=>{board.camera={x:0,y:0,zoom:1};applyCamera();queueSave();};
 canvas.addEventListener('wheel',event=>{event.preventDefault();zoomAt(board.camera.zoom*Math.exp(-event.deltaY*.0015),event.clientX,event.clientY);},{passive:false});
 svg.addEventListener('pointerdown',pointerDown);svg.addEventListener('pointermove',pointerMove);svg.addEventListener('pointerup',pointerUp);svg.addEventListener('pointercancel',pointerUp);
 document.addEventListener('keydown',event=>{if(!pageIsBoard() || ['TEXTAREA','INPUT'].includes(document.activeElement?.tagName) || document.activeElement?.isContentEditable)return;if(['Backspace','Delete'].includes(event.key) && selected){event.preventDefault();document.getElementById('board-delete').click();return;}if(event.metaKey && ['-','_','=','+','0'].includes(event.key)){event.preventDefault();if(event.key==='0')document.getElementById('board-home-view').click();else document.getElementById(event.key==='-' || event.key==='_'?'board-zoom-out':'board-zoom-in').click();}});
 const pageIsBoard=()=>!document.getElementById('overview').classList.contains('hidden');
 new ResizeObserver(applyCamera).observe(canvas);setTool('select');render();return {setBoard,getBoard:()=>clone(board)};
}
